name: flood_prediction
channels:
  - conda-forge
  - defaults
dependencies:
  - awscli
  - cartopy
  - cdsapi
  - dask
  - dask-glm
  - dask-ml
  - gdal
  - gcsfs
  - geopandas
  - geos
  - geotiff
  - google-api-python-client
  - graphviz
  - h5py
  - hdf4
  - hdf5
  - ipykernel
  - ipython
  - ipython_genutils
  - joblib
  - jupyter_client
  - jupyter_core
  - keras
  - keras-applications
  - keras-preprocessing
  - matplotlib
  - netcdf4
  - numba
  - numpy
  - pandas
  - pip
  - pyproj
  - python-graphviz
  - py-xgboost
  - rasterio
  - s3fs
  - scikit-learn
  - scipy
  - seaborn
  - setuptools
  - shapely
  - sip
  - six
  - snuggs
  - sortedcontainers
  - sqlite
  - statsmodels
  - tblib
  - tensorboard
  - tensorflow=1.13.1
  - termcolor
  - tk
  - toolz
  - tornado
  - tqdm
  - traitlets
  - urllib3
  - wcwidth
  - werkzeug
  - wheel
  - xarray
  - yaml
  - pyshp
  - pydot
