"backend: tensorflow\nclass_name: Sequential\nconfig:\n  build_input_shape: !!python/tuple\n\
  \  - null\n  - 13\n  layers:\n  - class_name: Dense\n    config:\n      activation:\
  \ tanh\n      activity_regularizer: null\n      bias_constraint: null\n      bias_initializer:\n\
  \        class_name: Zeros\n        config: {}\n      bias_regularizer: null\n \
  \     dtype: float32\n      kernel_constraint: null\n      kernel_initializer:\n\
  \        class_name: VarianceScaling\n        config:\n          distribution: uniform\n\
  \          mode: fan_avg\n          scale: 1.0\n          seed: null\n      kernel_regularizer:\
  \ null\n      name: dense_1\n      trainable: true\n      units: 64\n      use_bias:\
  \ true\n  - class_name: BatchNormalization\n    config:\n      axis: -1\n      beta_constraint:\
  \ null\n      beta_initializer:\n        class_name: Zeros\n        config: {}\n\
  \      beta_regularizer: null\n      center: true\n      dtype: float32\n      epsilon:\
  \ 0.001\n      gamma_constraint: null\n      gamma_initializer:\n        class_name:\
  \ Ones\n        config: {}\n      gamma_regularizer: null\n      momentum: 0.99\n\
  \      moving_mean_initializer:\n        class_name: Zeros\n        config: {}\n\
  \      moving_variance_initializer:\n        class_name: Ones\n        config: {}\n\
  \      name: batch_normalization_1\n      scale: true\n      trainable: true\n \
  \ - class_name: Dropout\n    config:\n      dtype: float32\n      name: dropout_1\n\
  \      noise_shape: null\n      rate: 0.25\n      seed: null\n      trainable: true\n\
  \  - class_name: Dense\n    config:\n      activation: linear\n      activity_regularizer:\
  \ null\n      bias_constraint: null\n      bias_initializer:\n        class_name:\
  \ Zeros\n        config: {}\n      bias_regularizer: null\n      dtype: float32\n\
  \      kernel_constraint: null\n      kernel_initializer:\n        class_name: VarianceScaling\n\
  \        config:\n          distribution: uniform\n          mode: fan_avg\n   \
  \       scale: 1.0\n          seed: null\n      kernel_regularizer: null\n     \
  \ name: dense_2\n      trainable: true\n      units: 1\n      use_bias: true\n \
  \ name: sequential_1\nkeras_version: 2.3.1\n"
